//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityProjeDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLPERSONEL
    {
        public int PERSONID { get; set; }
        public string PERSONADSOYAD { get; set; }
        public Nullable<int> PERSONSIFRE { get; set; }
        public string PERSONSEHIR { get; set; }
    }
}
